stages:
  - prep-codebase-analysis
  - code-explorer          # produce CIS
  - pm                     # PRD refresh
  - ux_designer(optional)
  - po
  - architect
  - arch-integrity         # run coacoa/quality/architecture_integrity.md
  - arch-integrity
  - scrum-master
  - dev
  - qa