stages:
  - prep-codebase-analysis
  - code-explorer          # produce CIS + artifact validation
  - schema-validation       # validate all artifacts against schemas  
  - pm                     # PRD refresh
  - ux_designer(optional)
  - po
  - architect
  - arch-integrity         # run coacoa/quality/architecture_integrity.md
  - scrum-master
  - dev
  - qa
  - final-validation       # validate all final outputs