name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Run tests & coverage
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pytest --cov=coacoa --cov-report=xml
          mkdir .github/assets
          coverage-badge -o .github/assets/coverage.svg -f       # ← creates/overwrites badge
      - name: Upload badge as artefact   # optional – lets you download it
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/assets/coverage.svg
      - name: Commit coverage badge
        if: success()
        run: |
          git config user.name "CoaCoA Bot"
          git config user.email "ci@localhost"
          git add .github/assets/coverage.svg
          git commit -m "chore(ci): update coverage badge" || echo "No badge changes"
          git push origin HEAD:${{ github.ref }}