name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run tests & coverage
        run: |
          python3 -m pip install --upgrade pip
          pip install -e ".[dev]"
          pytest --cov=coacoa --cov-report=xml
          coverage-badge -o .github/assets/coverage.svg -f       # ← creates/overwrites badge
      - name: Upload badge as artefact   # optional – lets you download it
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/assets/coverage.svg
      - name: Commit coverage badge
        if: success()
        run: |
          git config user.name "Shashank S"
          git config user.email "procodere@gmail.com"
          git add .github/assets/coverage.svg
          git commit -m "chore(ci): update coverage badge" || echo "No badge changes"
          git push origin HEAD:${{ github.ref }}